version: '2'

services:
  inventory-master-frontend:
    container_name: inventory-master-frontend
    image: inventory-master-frontend:0.0.1
    build: .
    volumes:
    - ./frontend:/app/frontend
    ports:
      - 1011:1011
    restart: always